server:
  port: 8081

spring:
  application:
    name: product-catalog
#  cloud:
#    config:
#      uri: http://localhost:8888
  h2:
    console:
      enable: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/Documents/module-product
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  debug: true